### ISSUE TITLE
mac下，运行make,遇错

### ISSUE THREAD

**Issue by luckypoem** [boytm/mproxy#1]
...
4 warnings generated.
[ 53%] Building C object CMakeFiles/mproxy.dir/evhtp_sock_relay.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -DENABLE_SS=1 -DUSE_CRYPTO_OPENSSL=1 -g -isystem /usr/local/include -isystem /opt/local/include -I/Users/yuming/mproxy/libevhtp -I/Users/yuming/mproxy/libevhtp/compat    -o CMakeFiles/mproxy.dir/evhtp_sock_relay.c.o   -c /Users/yuming/mproxy/evhtp_sock_relay.c
[ 61%] Building C object CMakeFiles/mproxy.dir/lru.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -DENABLE_SS=1 -DUSE_CRYPTO_OPENSSL=1 -g -isystem /usr/local/include -isystem /opt/local/include -I/Users/yuming/mproxy/libevhtp -I/Users/yuming/mproxy/libevhtp/compat    -o CMakeFiles/mproxy.dir/lru.c.o   -c /Users/yuming/mproxy/lru.c
/Users/yuming/mproxy/lru.c:231:49: warning: format specifies type
      'unsigned short' but the argument has type 'evhtp_error_flags'
      (aka 'unsigned char') [-Wformat]
                        bi->parent->hostname, (int)bi->parent->port, errtype);
                                                                     ^~~~~~~
/Users/yuming/mproxy/log.h:102:53: note: expanded from macro 'LOGD'
#define LOGD(fmt, ...) LOG(LOG_LEVEL_DEBUG, fmt, ## __VA_ARGS__)
                                                    ^~~~~~~~~~~
/Users/yuming/mproxy/log.h:90:124: note: expanded from macro 'LOG'
  ...PRIORITY_TO_STRING(prio), __FILENAME__, ## __VA_ARGS__);          \
                                                ^~~~~~~~~~~
1 warning generated.
[ 69%] Building C object CMakeFiles/mproxy.dir/utils.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -DENABLE_SS=1 -DUSE_CRYPTO_OPENSSL=1 -g -isystem /usr/local/include -isystem /opt/local/include -I/Users/yuming/mproxy/libevhtp -I/Users/yuming/mproxy/libevhtp/compat    -o CMakeFiles/mproxy.dir/utils.c.o   -c /Users/yuming/mproxy/utils.c
[ 76%] Building C object CMakeFiles/mproxy.dir/log.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -DENABLE_SS=1 -DUSE_CRYPTO_OPENSSL=1 -g -isystem /usr/local/include -isystem /opt/local/include -I/Users/yuming/mproxy/libevhtp -I/Users/yuming/mproxy/libevhtp/compat    -o CMakeFiles/mproxy.dir/log.c.o   -c /Users/yuming/mproxy/log.c
[ 84%] Building C object CMakeFiles/mproxy.dir/ss_connector.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -DENABLE_SS=1 -DUSE_CRYPTO_OPENSSL=1 -g -isystem /usr/local/include -isystem /opt/local/include -I/Users/yuming/mproxy/libevhtp -I/Users/yuming/mproxy/libevhtp/compat    -o CMakeFiles/mproxy.dir/ss_connector.c.o   -c /Users/yuming/mproxy/ss_connector.c
[ 92%] Building C object CMakeFiles/mproxy.dir/encrypt.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -DENABLE_SS=1 -DUSE_CRYPTO_OPENSSL=1 -g -isystem /usr/local/include -isystem /opt/local/include -I/Users/yuming/mproxy/libevhtp -I/Users/yuming/mproxy/libevhtp/compat    -o CMakeFiles/mproxy.dir/encrypt.c.o   -c /Users/yuming/mproxy/encrypt.c
[100%] Linking C executable mproxy
/usr/local/Cellar/cmake/3.3.1/bin/cmake -E cmake_link_script CMakeFiles/mproxy.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -g -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/mproxy.dir/connector.c.o CMakeFiles/mproxy.dir/evhtp_proxy.c.o CMakeFiles/mproxy.dir/evhtp_sock_relay.c.o CMakeFiles/mproxy.dir/lru.c.o CMakeFiles/mproxy.dir/utils.c.o CMakeFiles/mproxy.dir/log.c.o CMakeFiles/mproxy.dir/ss_connector.c.o CMakeFiles/mproxy.dir/encrypt.c.o  -o mproxy  libevhtp/libevhtp.a /usr/local/lib/libevent.dylib -lrt /opt/local/lib/libcrypto.dylib 
ld: library not found for -lrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [mproxy] Error 1
make[1]: *** [CMakeFiles/mproxy.dir/all] Error 2
make: *** [all] Error 2
yudeMacBook-Air:mproxy brite$

如何解决？谢谢你

**Comment by boytm** [comment]
上面是说没有 rt 这个库。这个 rt 库本来是 libevent 使用 clock_gettime() 之后需要的，只有链接 静态 libevent 时候才需要 rt 库的。  
你把这行 https://github.com/boytm/mproxy/blob/master/CMakeLists.txt#L44 的 rt 去掉试试，就是改成 set(MPROXY_LIBS ${MPROXY_LIBS} )  即可。

**Comment by luckypoem** [comment]
哦，搞好了。
服务器上，我是这样运行的：
root@RegalMusty-VM:~# ps aux|grep mproxy
root      1712  0.0  0.1  11228   872 pts/1    S+   21:56   0:00 grep --color=auto mproxy
root      2100  0.0  0.0  17444   336 ?        S    10:09   0:00 ./mproxy -l 9091 -k my-key -m aes-256-cfb
root@RegalMusty-VM:~# 
这样运行,对吗

mac上，该怎么运行呢？
谢谢你

**Comment by luckypoem** [comment]
我这样运行：
yudeMacBook-Air:mproxy brite$ ./mproxy -b127.0.0.1 -l8087 -s my-vps-ip -p 9091 -k my-key -m aes-256-cfb
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[11:15:43] INFO evhtp_proxy.c:[666]: listen at 127.0.0.1:8087
[11:16:52] ERROR evhtp_proxy.c:[86]: evhtp backend req 0x7fb2b4406200 error 17 while transport HTTP header

遇错。
如何解决？谢谢你

**Comment by boytm** [comment]
你 ss 密码不对吧，那端主动关闭了

**Comment by luckypoem** [comment]
先问一下，我在服务器上运行的你这个命令：./mproxy -l 9091 -k my-key -m aes-256-cfb是否也是ss服务端呢？

**Comment by boytm** [comment]
这个软件仅仅是 ss 客户端、或者 HTTP 代理。

./mproxy -l 9091 -k my-key -m aes-256-cfb  是启动 ss 客户端，还需要 -s 和 -p 参数指定 ss 服务端地址和IP。

wiki里面有详细介绍：https://github.com/boytm/mproxy/wiki/%E4%BD%9C%E4%B8%BA-shadowsocks-%E7%9A%84-%E5%AE%A2%E6%88%B7%E7%AB%AF-%E4%BD%BF%E7%94%A8

**Comment by luckypoem** [comment]
brew install libevent
brew link --overwrite libevent

这样，解决“运行make,遇错”的问题更省事。
